version: "3.7"

networks:
  web:
    external: true
  game_net:
    driver: bridge

services:
  web_game_class:
    build: ../frontend
    container_name: web_game_class
    networks:
      - web
      - game_net
    depends_on:
      - web_game_class_api
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webclass.rule=Host(`webclass.erikna.com`)"
      - "traefik.http.routers.webclass.entrypoints=web, websecure"
      - "traefik.http.routers.webclass.tls=true"
      - "traefik.http.routers.webclass.tls.certresolver=production"
  web_game_class_api:
    build: .
    container_name: web_game_class_api
    depends_on:
      - redis_web_class_api
    restart: always
    labels:
      - traefik.enable=false
    networks:
      - web
      - game_net
  redis_web_class_api:
    image: redis
    container_name: redis_web_class_api
    command: redis-server --port 6020 --requirepass Utc30rgaq*
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    restart: always
    volumes:
      - game_redis_data:/data
    networks:
      - game_net

volumes:
  game_redis_data:
