version: "3.7"

networks:
  web:
    external: true

services:
  web_game_class_api:
    build: .
    container_name: web_game_class_api
    ports:
      - "8030:8030"
    labels:
      - traefik.enable=true
      - traefik.http.routers.webclassapi.rule=Host(`webclassapi.erikna.com`)
      - traefik.http.routers.webclassapi.entrypoints=web, websecure
      - traefik.http.routers.webclassapi.tls=true
      - traefik.http.services.webclassapi.loadbalancer.server.port=8030
      - traefik.http.routers.webclassapi.tls.certresolver=production
    networks:
      - web
    restart: unless-stopped
